const constants = {

	GET_BITCOIN_BALANCE: 'GET_BITCOIN_BALANCE',
	UPDATE_BITCOIN_ADDRESS: 'UPDATE_BITCOIN_ADDRESS',
	GET_BALANCE_DATA_RECEIVED: 'GET_BALANCE_DATA_RECEIVED',
	UPDATE_TABLE_SORT_ORDER: 'UPDATE_TABLE_SORT_ORDER',
	PERFORM_TABLE_SORT: 'PERFORM_TABLE_SORT',
	
	ADD_NOTIFICATION_BANNER: 'ADD_NOTIFICATION_BANNER',
	CLEAR_NOTIFICATION_BANNER: 'CLEAR_NOTIFICATION_BANNER',
	CHOSE_NAV_BAR_ITEM: 'CHOSE_NAV_BAR_ITEM',
	TOGGLE_ADDRESS_FORM: 'TOGGLE_ADDRESS_FORM',
	CLEAR_ADDRESS_FORM: 'CLEAR_ADDRESS_FORM',
	
	/* APIS */
	get_bitcoin_balance_url: 'https://api.ledgerwallet.com/blockchain/v2/btc/addresses/'
}

export default constants
